language: python
python:
  - 2.6
  - 2.7
  - pypy

install:
  - pip install --use-mirrors -q mock nose PyHamcrest python-coveralls pyflakes
  - python setup.py -q install
script:
  - python --version
  - nosetests --with-coverage
  - COVERAGE_FILE=.coverage.features coverage run bin/beehive -f progress3 --junit --tags=~@xfail features/
  - COVERAGE_FILE=.coverage.tools coverage run bin/beehive -f progress3 --junit --tags=~@xfail tools/test-features/
  - COVERAGE_FILE=.coverage.issues coverage run bin/beehive -f progress3 --junit --tags=~@xfail issue.features/
  - pyflakes beehive beehive4cmd0 issue.features more.features features
after_success:
  - coverage combine
  - coveralls
