language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - pypy

install:
  - pip install --use-mirrors -q mock nose PyHamcrest codecov pyflakes pep8
  - python setup.py -q install
script:
  - python --version
  - nosetests --with-coverage --cover-branches
  - COVERAGE_FILE=.coverage.features coverage run --branch bin/beehive -f progress3 --junit --tags=~@xfail features/
  - COVERAGE_FILE=.coverage.tools coverage run --branch bin/beehive -f progress3 --junit --tags=~@xfail tools/test-features/
  - COVERAGE_FILE=.coverage.issues coverage run --branch bin/beehive -f progress3 --junit --tags=~@xfail issue.features/
  - pyflakes **/*.py
  - pep8 --ignore=E501,E265 --show-source --show-pep8 **/*.py
after_success:
  - coverage combine
  - coverage xml
  - codecov
